Rebrand from CBPP to OxyOS

diff --git a/data/usr/bin/oxyos-compositor b/data/usr/bin/oxyos-compositor
--- a/data/usr/bin/oxyos-compositor
+++ b/data/usr/bin/oxyos-compositor
@@ -1,15 +1,13 @@
 #!/bin/bash
-# cbpp-compton
+# oxyos-compton
 # Openbox Pipe Menu for use with compton compositor
-# Written for CrunchBang Linux <http://crunchbang.org/>
-# by Philip Newborough <corenominal@corenominal.org>
-# Ported to #!++ <https://crunchbangplusplus.org>
-# by Ben Young <computermouth@crunchbangplusplus.org>
+# Written for OxyOS <https://oxyos.org/>
+# Originally by Philip Newborough <corenominal@corenominal.org>
 
 RESTART_ATTEMPTS=20
 
-if ! . cbpp-include.cfg 2> /dev/null; then
-    echo '  Failed to locate cbpp-include.cfg in PATH' >&2
+if ! . oxyos-include.cfg 2> /dev/null; then
+    echo '  Failed to locate oxyos-include.cfg in PATH' >&2
     exit 1
 fi
 
@@ -47,22 +45,22 @@ elif [[ $1 = '--restart' ]]; then
 
         sleep 0.25
     done
-    cbpp-compositor --start
+    oxyos-compositor --start
 elif [[ $1 = '--watch' ]]; then
     while inotifywait -e modify "$HOME/.config/compton.conf"; do
-        cbpp-compositor --restart # TODO move this to function?
+        oxyos-compositor --restart # TODO move this to function?
     done
 else
     # Output Openbox menu
     menuStart
     if ! pidof compton > /dev/null; then
-        menuItem 'Enable Compositing' 'cbpp-compositor --start'
+        menuItem 'Enable Compositing' 'oxyos-compositor --start'
     else
-        menuItem 'Restart Compositing' 'cbpp-compositor --restart'
-        menuItem 'Disable Compositing' 'cbpp-compositor --toggle'
+        menuItem 'Restart Compositing' 'oxyos-compositor --restart'
+        menuItem 'Disable Compositing' 'oxyos-compositor --toggle'
         menuSeparator
     fi
-    menuItem 'Edit Compositing Settings' 'cbpp-compositor --edit'
+    menuItem 'Edit Compositing Settings' 'oxyos-compositor --edit'
     menuEnd
 fi
 exit 0
diff --git a/data/usr/bin/oxyos-power-pipemenu b/data/usr/bin/oxyos-power-pipemenu
--- a/data/usr/bin/oxyos-power-pipemenu
+++ b/data/usr/bin/oxyos-power-pipemenu
@@ -1,40 +1,39 @@
 #!/bin/bash
 # ---------------------------------------------------------------------
 # An Openbox pipemenu for use with powerprofilesctl.
-# Written for CrunchBangPlusPlus (#!++) <https://crunchbangplusplus.org>
-# by Ben Young <computermouth@crunchbangplusplus.org>
+# Written for OxyOS <https://oxyos.org/>
 # ---------------------------------------------------------------------
 
-if ! . cbpp-include.cfg 2> /dev/null; then
-    echo '  Failed to locate cbpp-include.cfg in PATH' >&2
+if ! . oxyos-include.cfg 2> /dev/null; then
+    echo '  Failed to locate oxyos-include.cfg in PATH' >&2
     exit 1
 fi
 
 if [[ $1 = '--install' ]]; then
-    x-terminal-emulator --title='Install PPD' --command='cbpp-power-pipemenu --install-ppd'
+    x-terminal-emulator --title='Install PPD' --command='oxyos-power-pipemenu --install-ppd'
 
 elif [[ $1 = '--install-ppd' ]]; then
     promptInstall 'PPD' 'Power Profiles Daemon' 'power-profiles-daemon'
 
 else
-    
+
     e_current='None'
     e_modes=('No Modes Detected')
-    
+
     current=$(powerprofilesctl list | grep '*' | tr -d '* :')
     if [ "x$current" == "x" ]; then
 		current=$e_current
     fi
-    
+
     modes=$(powerprofilesctl | sed -n -E 's/^[ *]*([a-zA-Z-]+):$/\1/p')
     if [ "x$modes" == "x" ]; then
 		modes=$e_modes
     fi
-    
+
     # Pipemenu
     menuStart
     menuSeparator "Current Mode: $current"
-    
+
     for mode in $modes; do
 		title=" "
 		if [ "x$mode" == "x$current" ]; then
@@ -42,8 +41,8 @@ else
 		fi
 		menuItem "$title $mode" "powerprofilesctl set $mode"
     done
-    
+
     menuEnd
-    
+
 fi
 exit 0
